name: Build and Release Packages

on:
  push:
    tags: [ 'v*' ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build ${{ matrix.arch }}-${{ matrix.version }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        version:
          - 25.12.5
          - 24.10.0

        arch:
          # ARM64
          - aarch64_cortex-a53
          - aarch64_cortex-a72
          - aarch64_generic

          # ARM32
          - arm_cortex-a7_neon-vfpv4
          - arm_cortex-a9_vfpv3-d16
          - arm_cortex-a15_neon-vfpv4

          # MIPS
          - mips_24kc
          - mipsel_24kc

          # x86
          - x86_64

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Build package
        uses: openwrt/gh-action-sdk@main
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.version }}
          PACKAGES: darkmoon
          IGNORE_ERRORS: 0

      - name: Collect packages
        run: |
          mkdir -p dist

          find bin/packages -type f \
            \( -name "*.apk" -o -name "*.ipk" \) \
            | while read file; do
                cp "$file" "dist/${{ matrix.arch }}_$(basename "$file")"
              done

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: darkmoon-${{ matrix.arch }}-${{ matrix.version }}
          path: dist/*

      - name: Publish Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
